-- views materializadas do dashboard, a escrever quando as tabelas estiverem povoadas:
-- mv_raio_atuacao_anual (QP1), mv_influenciadores (QP2), mv_mercado_ti_real (QP3),
-- mv_retencao_regional (H2), mv_impacto_per_capita (H4), mv_eficiencia_absorcao (H6)
